# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:  恬静的小魔龙
subtitle: 公众号:恬静的小魔龙 「欢迎关注个人公众号」
name: 恬静的小魔龙 
email: 764424567@qq.com
description: 本站为恬静的小魔龙的技术分享博客。内容涵盖Java后端技术、Web前端等相关知识分享，还有有趣的程序人生等着你。
keywords: 恬静的小魔龙,Java,Java教程,程序人生,程序员,前端,Web,全栈
encoding: "utf-8"
favicon: favicon.ico 

repository: 764424567/764424567.github.io
github_url: https://github.com/764424567
url: http://www.qq764424567.top
enforce_ssl: qq764424567.top

## Gem
plugins:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true
  syntax_highlighter: rouge

syntax_highlighter_opts:
   coderay_line_numbers:  nil

# Pagination
paginate: 12
paginate_path: 'page:num'

# Navigation. top menu list
menus:

  -
    href: /zsxq.html
    label: 星球
    target: _self

  -
    href: /link.html
    label: 友链
    target: _self



# Navigation. main menu list
navs:

  -
    href: /
    label: Home

  -
    href: /Unity3D.html
    label: Unity3D
    target: _self
    subnav:

      -
        subHref: /Unity3D-Study.html
        subLabel: Unity3D自学之路

      -
        subHref: /Unity3D-Game.html
        subLabel: Unity3D开发小游戏
        
      -
        subHref: /Unity3D-Daily.html
        subLabel: Unity3D日常开发
  -
    href: /web.html
    label: C#编程
    target: _self
    
  -
    href: /life.html
    label: 程序人生
    target: _self
    
  -
    href: /share.html
    label: 算法
    target: _self


  -
    href: /archives.html
    label: Archives
    target: _self

  -
    href: /about.html
    label: About
    target: _self


# labels. my blog key words
labels:

  -
    href: /open-source.html
    label: GitHub库  
    target: _blank


# selected articles
classes:

  -
    href: /Unity3D.html
    name: Unity3D
    describe: 分享Unity3D的日常使用技巧


  -
    href: /web.html
    name: C# 系列文章
    describe: C#是用Unity开发软件的语言，Unity3D 程序员必学


# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# Sidebar to show popular repo
side_bar_repo_limit: 6 # Number of repos to show

# Google Analytics
# analytics :
# provider : google
#   google :
#     tracking_id : ''  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, MySQL, Oracle, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, NodeJS, ExpressJS, MongoDB, Redis, PHP,  Boostrap]
skill_mobile_app_keywords: [vuejs, hyhird app]


# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 764424567
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: 764424567
    repo: blog-comments
    oauth:
        client_id: f850d0f18b59784e6480
        client_secret: 665bbd6b5e26be321f64909c1d3288962aed81de
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: 764424567
    repo: blog-comments
    clientID: f850d0f18b59784e6480
    clientSecret: 665bbd6b5e26be321f64909c1d3288962aed81de
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true
